spring:
  profiles:
    group:
      local: "local-envs,local-db"
      dev: ""
      production: ""
    active: local

#security:
#  jwt:
#    key-value: 2AA4B45D5FB9FF29B722A57E3E9FAAF4F2DC33326953338C5F9B92783E


---
# local env
spring:
  config:
    activate:
      on-profile: local-envs
server:
  port: 8080

---
# local db
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true